name: hindu_calendar
description: Hindi-first, offline Hindu Panchang calendar.
publish_to: 'none'
version: 0.4.0+4

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/festival_overrides.json
